apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: luadns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: luadns

  data:
    - secretKey: api_username
      remoteRef:
        key: LUADNS_API_USERNAME
    - secretKey: api_token
      remoteRef:
        key: LUADNS_API_TOKEN