apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/secretstore.yaml

helmCharts:
  - name: external-secerts
    repo: https://charts.external-secerts.io
    version: 1.2.0
    releaseName: external-secrets
    namespace: external-secerts
    valuesFile: values.yaml
