apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/oauth-client-secret.yaml
  - resources/proxy-group.yaml

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.92.4
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: values.yaml
