apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/secretstore.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 1.2.0
    releaseName: external-secrets
    namespace: external-secrets
    apiVersions:
    - monitoring.coreos.com/v1
    valuesFile: values.yaml
    includeCRDs: true
