apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/csi-homelab-seceret.yaml

helmCharts:
  - name: proxmox-csi-plugin
    repo: oci://ghcr.io/sergelogvinov/charts
    version: 0.5.4
    releaseName: proxmox-csi-plugin
    namespace: proxmox-csi
    valuesFile: values.yaml
