apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/luadns-secret.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 38.0.1
    releaseName: traefik 
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
